import jax
import jax.numpy as jnp
from functools import partial
from config import TGPOConfig

class EliteBuffer:
    def __init__(self, n_vars, capacity=TGPOConfig.BATCH_SIZE):
        """
        Elite Buffer: Maintains the top-K time variables with highest STL robustness.
       
        
        Args:
            n_vars: Dimension of the time variable (e.g. 2, corresponding to the time to go to A and B)
            capacity: Buffer size, usually set to BATCH_SIZE (512)
        """
        self.capacity = capacity
        self.n_vars = n_vars
        
        # --- Initialize State ---
        # 1. Initializing Time Variable Storage (Full 0)
        # shape: (512, 2)
        self.times = jnp.zeros((capacity, n_vars))
        
        # 2. Initialize fraction storage (negative infinity)
        # set to -1e9 to guarantee any true (even negative) STL score on the first update
        # can squeeze out these initial placeholders.
        # shape: (512,)
        self.scores = jnp.full((capacity,), -1e9)

    @partial(jax.jit, static_argnums=(0,))
    def update(self, current_times, current_scores, batch_new_times, batch_new_scores):
        """
        Strict Update Logic: Merge -> Sort -> Truncate
        
        Args:
            current_times: Existing times in Buffer (State.times)
            current_scores: Existing scores in Buffer (State.scores)
            batch_new_times: All time generated by the rollout (Candidates)
            batch_new_scores: STL score (Rho) calculated from this round of rollout
            
        Returns:
            new_times, new_scores: Updated Buffer data
        """
        # 1. Merge
        # Put the "old elite" and "new challenger" in the same pool
        # shape: (1024, n_vars) if batch=512
        all_times = jnp.concatenate([current_times, batch_new_times], axis=0)
        # shape: (1024,)
        all_scores = jnp.concatenate([current_scores, batch_new_scores], axis=0)
        
        # 2. Sort
        # jnp.argsort defaults to ascending order (from smallest to largest)
        sort_idx = jnp.argsort(all_scores)
        
        # 3. Truncate Top-K (Truncate)
        # We need the maximum score.
        # slice [-self.capacity:] takes the last K, which is the largest K
        # Note: This way the extraction is "from small to large" rows, but this is okay for the collection
        top_k_idx = sort_idx[-self.capacity:]
        
        # Extract the corresponding data
        new_times = all_times[top_k_idx]
        new_scores = all_scores[top_k_idx]
        
        return new_times, new_scores

    @partial(jax.jit, static_argnums=(0, 2))
    def sample(self, current_times, n_sample, rng_key):
        """
        [Modified version] Greedy Sampling: 
        Ignore randomness and take the top-N samples with the highest scores in the buffer.
        
        Args:
            current_times: The times here are already in ascending order of score (from smallest to largest).
            n_sample: The number of samples that need to be sampled.
            rng_key: (no longer used in this release, but retains interface compatibility)
            
        Returns:
            sampled_times: (n_sample, n_vars) The best time parameters
        """
        # Because current_times are in ascending order, the best is at the end.
        # We slice directly to take the last n_sample.
        # For example: If n_sample=50, we take [-50:]

        idx = jax.random.randint(
            rng_key,
            shape=(n_sample,),
            minval=0,
            maxval=self.capacity
        )

        # Gather

        sampled_times = current_times[idx] 
        return sampled_times